### PR TITLE
Remove Flutter

### PR DESCRIPTION
**Pull request by LiorAgnin**

### CODE REVIEW

**Comment by inveker** [comment]
Hello! I looked at your code, can you explain what is the essence of your PR? By the commit names, it looks like you removed the flutter dependency, but there are changes in the code that have nothing to do with it

**Comment by LiorAgnin** [comment]
Hi @inveker, Yes. I removed the flutter dependency, and mistakenly did some weird things. I removed them In the last commit. Can you go over the PR again?

**Comment by inveker** [comment]
Thanks @LiorAgnin, I've merged into the develop branch, made a few edits. One of these days I will check and merge into main with a new patch

**Comment by inveker** [comment]
@LiorAgnin Hello, I have updated the package to version 0.0.3 which includes your work.

**Pull request merged**
